version: '3.8'

services:

  app:
    image: {{.Name}}
    build: .
    depends_on:
    {{if .Databases}}
      {{- range .Databases }}
      - {{.}}
      {{- end}}
    {{- end}}
    networks:
      - {{.Module}}
    ports:
      - {{.Port}}
    
{{if .Databases}}
  {{- $module := .Module}}
  {{- range .Databases }}
  {{.}}:
    extends:
      file: {{.}}.yaml
      service: db
    networks:
      - {{$module}}
  {{- end}}
{{- end}}

  adminer:
    extends:
      file: db.yaml
      service: adminer
    networks:
      - {{.Module}}

networks:
  {{.Module}}: