version: '3.8'

services:

  app:
    depends_on:
      - db

  db:
    extends:
      file: db.yaml
      service: db
    networks:
      - {{.Module}}

  adminer:
    extends:
      file: db.yaml
      service: adminer
    networks:
      - {{.Module}}

networks:
  {{.Module}}: