version: '3.8'

services:

  app:
    image: {{.Name}}
    build: .
    depends_on:
    {{if .Databases}}
      {{- range $db := .Databases }}
      - {{$db}}
      {{- end}}
    {{- end}}
    networks:
      - {{.Module}}
    ports:
      - {{.Port}}
    
{{if .Databases}}
  {{- range $db := .Databases }}
  {{$db}}:
    extends:
      file: {{$db}}.yaml
      service: db
    networks:
      - {{.Module}}
  {{- end}}
{{- end}}

  adminer:
    extends:
      file: db.yaml
      service: adminer
    networks:
      - {{.Module}}

networks:
  {{.Module}}: