version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: {{.DatabasePassword}}
      DATABASE_USER: {{.Module}}
      DATABASE_PASSWORD: {{.Module}}
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: {{.DatabasePassword}}

volumes:
  data-volume:
