version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: {{.Password}}
      POSTGRES_USER: {{.Module}}
      POSTGRES_DB: {{.Nodule}}
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data-volume: